function [ ecg_out ] = myFilter( ecg ,fs)
%MYFILTER 此处显示有关此函数的摘要
%   此处显示详细说明


% filters = designfilt('bandpassiir', 'FilterOrder', 20, ...
%                      'PassbandFrequency1', 20, 'PassbandFrequency2', ...
%                      130, 'PassbandRipple', 1, 'SampleRate', fs, ...
%                      'DesignMethod', 'cheby1');
% 
% ecg_out = filter(filters, ecg);

filters2 = designfilt('bandstopiir', ...
    'PassbandFrequency1', 45,...
    'StopbandFrequency1', 48,...
    'StopbandFrequency2', 52,...
    'PassbandFrequency2', 55,...
    'PassbandRipple1', 1,...
    'StopbandAttenuation', 10,...
    'PassbandRipple2', 1,...
    'DesignMethod', 'butter',...
    'SampleRate', fs);
fvtool(filters2);

%filters2 = designfilt('bandstopiir', ...
%    'PassbandFrequency1', 20,...
%    'StopbandFrequency2', 46,...
%    'PassbandFrequency2', 70,...
%    'PassbandRipple1', 1,...
%    'StopbandAttenuation', 1.01,...
%    'PassbandRipple2', 1,...
%    'DesignMethod', 'butter',...
%    'SampleRate', fs);
% filters2 = designfilt('bandstopfir', 'CutoffFrequency1', 20, ...
%                      'CutoffFrequency21', 53, 'PassbandRipple1', ...
%                      1, 'SampleRate', fs);
% filters2 = designfilt('bandstopiir', 'FilterOrder', 8, ...
%                       'HalfPowerFrequency1', 20, 'HalfPowerFrequency2', ...
%                       60, 'SampleRate', fs, 'DesignMethod', 'butter');
% fvtool(filters2);


% filters2 = designfilt('bandpassiir', 'FilterOrder', 2, ...
%                      'PassbandFrequency1', 60, 'PassbandFrequency2', ...
%                      130, 'PassbandRipple', 1, 'SampleRate', 500, ...
%                      'DesignMethod', 'cheby1');
ecg_out = filter(filters2, ecg);

end






